export const ADD_COMMENT = 'ADD_COMMENT'
export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const PRODUCT_FAILED = 'PRODUCT_FAILED'
export const ADD_PRODUCT = 'ADD_PRODUCT'

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
